//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OITB
    {
        public string SkuCode { get; set; }
        public string BodegaCode { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> Asignado { get; set; }
        public Nullable<decimal> Ordenado { get; set; }
        public Nullable<decimal> Costo { get; set; }
    }
}
