//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OITM
    {
        public string ProdCode { get; set; }
        public string ProdNombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CategoriaCode { get; set; }
        public string TipoCode { get; set; }
        public Nullable<int> FamiliaCode { get; set; }
        public Nullable<int> AnimalCode { get; set; }
        public Nullable<int> FormatoCode { get; set; }
        public Nullable<int> RefrigeraCode { get; set; }
        public string Activo { get; set; }
        public string SocioCode { get; set; }
        public Nullable<int> MarcaCode { get; set; }
        public Nullable<int> ProcedenciaCode { get; set; }
        public string Medida { get; set; }
    }
}
