//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPED
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<System.DateTime> DocFecha { get; set; }
        public string SocioCode { get; set; }
        public Nullable<int> ContactoCode { get; set; }
        public Nullable<int> CondicionCode { get; set; }
        public Nullable<int> DireccionCode { get; set; }
        public Nullable<int> VendedorCode { get; set; }
        public string UsuarioCode { get; set; }
    }
}
