//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSCP
    {
        public string SocioCode { get; set; }
        public string Rut { get; set; }
        public string RazonSocial { get; set; }
        public string SocioTipo { get; set; }
        public string EmailSII { get; set; }
        public Nullable<int> RubroCode { get; set; }
        public string RubroName { get; set; }
        public Nullable<int> CondicionCode { get; set; }
        public string CondicionName { get; set; }
        public string VendedorCode { get; set; }
        public string MatrizSocio { get; set; }
        public Nullable<decimal> CreditoAutorizado { get; set; }
        public Nullable<decimal> CreditoUtiliado { get; set; }
        public string EstadoOperativo { get; set; }
        public string Giro { get; set; }
        public string NombreFantasia { get; set; }
    }
}
