//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED1
    {
        public int DocEntry { get; set; }
        public int DocLinea { get; set; }
        public string LineaEstado { get; set; }
        public string SkuCode { get; set; }
        public string SkuNombre { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioLista { get; set; }
        public Nullable<decimal> PrecioFinal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Pendiente { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseLinea { get; set; }
        public string BodegaCode { get; set; }
    }
}
