//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCP1
    {
        public int DireccionCode { get; set; }
        public string DireccionTipo { get; set; }
        public string SocioCode { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public Nullable<int> ComunaCode { get; set; }
        public Nullable<int> CiudadCode { get; set; }
        public Nullable<int> RegionCode { get; set; }
        public string ComunaNombre { get; set; }
        public string CiudadNombre { get; set; }
        public string RegionNombre { get; set; }
        public string HorarioAtencion { get; set; }
        public string Observaciones { get; set; }
        public string EmailDriveIn { get; set; }
        public Nullable<bool> PorDefecto { get; set; }
    }
}
