<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="mantenedor-grupos.aspx.cs" Inherits="Colonos.Web.mantenedor_grupos" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>
        <!-- INI POPUP EDITAR -->
        <asp:Panel ID="pnlEditar" runat="server" Style="display: none; width:90%;max-width:800px;">
            <div class="window-ficha-modal-sm" style="font-family: 'Ubuntu', sans-serif;">
                <div class="card-detail-window">
                    <div class="modal-content">
                        <div class="modal-header"  style="background-color: #a9202c; color:white;">
                            <asp:HiddenField ID="HiddenFieldSKU" runat="server" />
                            <h2><asp:Label ID="Label3" runat="server" ForeColor="black" CssClass="d-block" Text="Configuración Grupos de Usuario"></asp:Label></h2>
                            <asp:LinkButton ID="btnClosePopupEstanque" CssClass="btn-close" runat="server" OnClick="ClosePopupEditar"></asp:LinkButton>
                        </div>
                    
                        <div class="modal-body modal-body-max-height" >
                        
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group py-2">
                                        <label for="txtIdUsuario">Grupo</label>
                                        <asp:TextBox ID="txtIdGrupo" runat="server" CssClass="form-control" placeholder="Id Grupo"></asp:TextBox>
                                    </div>
                                    <div class="form-group py-2">
                                        <label for="txtUserName">Descripción</label>
                                        <asp:TextBox ID="txtDescripcion" runat="server" CssClass="form-control" placeholder="Descripcion"></asp:TextBox>
                                    </div>

                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                            <label for="cboAlmacenes">Accesos</label>
                                            <div style="max-height: 500px;background-color: white; border: 1px solid #c1c1c1; padding: 1em; overflow-y: auto;">
                                                <asp:TreeView ID="tvwDirectorio"  runat="server" AutoGenerateDataBindings="false" >
                                                </asp:TreeView>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="row w-100">
                                <div class="col-sm-6">
                                    <%--<asp:LinkButton ID="cmdElininar" runat="server" CssClass="float-start" Font-Size="20" ><i style="color:black;" class="fas fa-trash-alt fa-xl"></i></asp:LinkButton>--%>
                                
                                </div>
                                <div class="col-sm-6">
                                    <asp:Button ID="cmdActualizar" CssClass="btn btn-treck btn-sm float-end" ForeColor="#ffe500" BackColor="#1d1d1b" runat="server" OnClick="Guardar" Text="Guardar" />
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </asp:Panel>
        <!-- FIN POPUP EDITAR -->
        <header class="bg-white shadow-sm px-4 py-3 stycky-top60-body">
            <div class="container-fluid px-0">
                <h2 class="mb-0 p-1 h-size2em h-weight400">Mantener Grupos</h2>
            </div>
        </header>
        <main class="main-page shadow-lg p-3 mb-5 bg-body rounded">
            <div class="border-main-page">
                <div class="row">
                    <div class="col-md-12">
                        <div style="padding-left: 10px; padding-right: 10px;">
                            <div class="table-responsive p-1 table-dark-treck">
                                <asp:GridView ID="gvResultado" runat="server"
                                    AutoGenerateColumns="False"
                                    AllowPaging="false"
                                    CssClass="table table-sm table-bordered table-hover header-grid"
                                    HeaderStyle-CssClass="header-grid headfijo"
                                    RowStyle-CssClass="row-grid">
                                    <Columns>
                                        <asp:TemplateField HeaderText="IdGrupo" ItemStyle-HorizontalAlign="center">
                                            <ItemTemplate>
                                                <asp:Label ID="lblIdGrupo" runat="server"   Text='<%# Eval("IdGrupo")%>' />
                                            </ItemTemplate>
                                            <ItemStyle HorizontalAlign="Left" Width="5%"></ItemStyle>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Nombre">
                                            <ItemTemplate>
                                                <asp:LinkButton ID="lblDescripcion" runat="server" OnClick="Editar" Text='<%# Eval("Nombre")%>' />
                                            </ItemTemplate>
                                            <ItemStyle Width="25%"></ItemStyle>
                                        </asp:TemplateField>
                                    </Columns>
                                    <EmptyDataTemplate>
                                        <i class="fas fa-exclamation-circle fa-lg"></i>
                                        <span style="font-size: 15px; font-style: italic; margin-left: 5px;">Ningún registro encontrado...</span>
                                    </EmptyDataTemplate>
                                </asp:GridView>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <asp:LinkButton ID="lnkFake" runat="server"></asp:LinkButton>
    <cc1:ModalPopupExtender
        ID="popupEditar" runat="server"
        DropShadow="false"
        PopupControlID="pnlEditar"
        TargetControlID="lnkFake"
        BackgroundCssClass="modalBackground">
    </cc1:ModalPopupExtender>
</asp:Content>
