//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCP3
    {
        public int CondicionCode { get; set; }
        public string CondicionNombre { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<int> Orden { get; set; }
    }
}
