//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.EndPointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCP4
    {
        public string SocioCode { get; set; }
        public Nullable<System.DateTime> FechaCarpeta { get; set; }
        public Nullable<System.DateTime> FechaDicom { get; set; }
        public Nullable<decimal> Cod20 { get; set; }
        public Nullable<decimal> Cod142 { get; set; }
        public Nullable<decimal> Cod537 { get; set; }
        public Nullable<decimal> Cod538 { get; set; }
        public Nullable<decimal> Cod1400 { get; set; }
        public Nullable<decimal> Cod1410 { get; set; }
        public Nullable<decimal> Cod1430 { get; set; }
        public Nullable<decimal> Cod1610 { get; set; }
        public Nullable<decimal> Cod1629 { get; set; }
        public Nullable<decimal> Cod1657 { get; set; }
        public Nullable<decimal> Cod1661 { get; set; }
    }
}
